config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip =>  [:registrations], controllers:{
  	omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :eventos
  post 'evento/:id', to: 'eventos#delete_image', as: 'delete_image'
  get 'home/index'
  root to: 'home#index'
  get 'home/change_region'
  get 'home/politicas'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_evento.html.erb
<div class="section">
	<% @eventos.each do |e| %>
	    
	      <div class="card">
	        <div class="card-image">
	          <% if e.image.attached? %>
				<%= image_tag e.image.variant(resize: "600x600").processed %>
			  <% else %>
	         	<%= image_tag 'default-image.jpg' %>
	          <% end %>
	          <span class="card-title"><%= e.comuna.nombre %></span>
	          
	          <% if e.pertenece_to_user(current_user) %>
	          	<% if evento.present? %>
	          	 <a class="btn-floating halfway-fab waves-effect waves-light red" href="<%= evento_path(e) %>"><i class="material-icons">add</i></a>
	          	<% else %>
	          		 <a class="btn-floating halfway-fab waves-effect waves-light gren" href="<%= evento_path(e) %>"><i class="material-icons">memory</i></a>
		        <% end %>

	          <% else %>
	          	<a class="btn-floating halfway-fab waves-effect waves-light red" href="<%= evento_path(e) %>"><i class="material-icons">add</i></a>
	          <% end %>
	        </div>
	        <div class="card-content">
	          <% if evento.present? %>
	          	<%= raw e.descripcion.capitalize %>
	          <% else %>
	          	<%= raw e.descripcion.capitalize[0..30] + '...' %>
	          <% end %>
	        </div>
	      </div>
		
	<% end %>
</div>

app/views/shared/_eventos.html.erb
<div class="row">
	<% @eventos.each do |e| %>
		<div class="col s6">
	      <div class="card">
	        <div class="card-image card-image-petite">
       		 <% if e.image.attached? %>
				<%= image_tag e.image.variant(resize: "600x600").processed %>
			 <% else %>
	         	<%= image_tag 'default-image.jpg', size:"600x600" %>
	         <% end %>
	          <span class="card-title"><%= e.comuna.nombre %></span>
	          
	          
	          	<a class="btn-floating halfway-fab waves-effect waves-light <%= e.pertenece_to_user(current_user) ? 'green' : 'red' %>" href="<%= evento_path(e) %>"><i class="material-icons"><%= e.pertenece_to_user(current_user) ? 'edit' : 'add' %></i></a>
	          
	        </div>
	        <div class="card-content">
	          	<%= truncate(e.descripcion_short , length:30, omission: '...').html_safe %>
	        </div>
	      </div>
		</div>
	<% end %>
</div>    

app/views/shared/_footer.html.erb
 <footer class="page-footer #000000 black">
  <div class="container">
    <div class="row">
      <div class="col s6">
        <h5 class="white-text">GuerraSoft</h5>
        <p class="grey-text text-lighten-1">Nos limitamos a compartir información, entre personas.</p>
      </div>
      <div class="col s6 right-align">
      	<a class="btn-floating btn-large waves-effect waves-light red" id='close-footer'><i class="material-icons">clear</i></a>      
      </div>
    </div>
  </div>
  <div class="footer-copyright #000000 black">
    <div class="container">
    	© 2020 Copyright Text
    </div>
  </div>
</footer>

<script>
	
$(document).ready(function(){
	  dimensionar();
    
    function dimensionar(){
      
  		  $('body').css({paddingBottom: $(window).width() >= 768 && $(window).height() >= 500 ?
            $('footer').outerHeight() + 'px' : 
            '0'
        });
      
		};	

	  document.getElementById('close-footer').addEventListener('click',alerta,false);

	  function alerta() {
	  	$('footer').hide("slow");
	  	$('body').css({paddingBottom: '0px'});
	  }
	})
</script>

app/views/shared/_navbar.html.erb
 <nav>
	<div class="nav-wrapper #000000 black">
	  <%= image_tag 'olla.svg', class: 'logo brand-logo' %>
	  <a href="#" data-target="mobile-demo" class="sidenav-trigger" id="mobile-btn"><i class="material-icons">menu</i></a>
	  <ul class="right hide-on-med-and-down">
	    <li><%= link_to "Inicio",root_path %></li>
	    <% if user_signed_in? %>
	    	<li><%= current_user.email %></li>
	    	<li><%= link_to "Cerrar Sesion",destroy_user_session_path, method: :delete %></li>
	    <% else %>
	    	<li><%= link_to "Iniciar sesión", new_user_session_path %></li>
	    <% end %>

	   <% if user_signed_in? %>
	    <% if current_user.admin? %>
	    	<li><%= link_to "Eventos", eventos_path %></li>
	    <%  else %>
	    	<% if with_evento? %>
	    		<li><%= link_to "Tu Evento", evento_path(current_user.evento) %></li>
	    	<% else %>
	    		<li><%= link_to "Crea Tu Evento", new_evento_path %></li>
	    	<% end %>
	    <% end %>
	   <% end %> 
	  </ul>
	</div>
</nav>

<ul class="sidenav" id="mobile-demo">
	<li><%= link_to "Inicio",root_path %></li>
	<% if user_signed_in? %>
    	<li><%= link_to "Cerrar Sesion",destroy_user_session_path, method: :delete %></li>
    <% else %>
    	<li><%= link_to "Iniciar sesión", new_user_session_path %></li>
	<% end %>
	<% if user_signed_in? %>
	    <% if current_user.admin? %>
	    	<li><%= link_to "Eventos", eventos_path %></li>
	    <%  else %>
	    	<% if with_evento? %>
	    		<li><%= link_to "Tu Evento", evento_path(current_user.evento) %></li>
	    	<% else %>
	    		<li><%= link_to "Crea Tu Evento", new_evento_path %></li>
	    	<% end %>
	    <% end %>
	<% end %> 
</ul>

<script>
	$(document).ready(function(){
     $('.sidenav').sidenav();
  	});
</script>

app/views/shared/_notificar.html.erb
<script>
	$(document).ready(function(){
		var notice = "<%=j flash[:notice] %>"
		if (notice.length > 0) {
			M.toast({html: notice})
		}
		var alert = "<%=j flash[:alert] %>"
		if (alert.length > 0) {
			M.toast({html: alert})
		}
	})
</script>