config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip =>  [:registrations], controllers:{
  	omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :eventos
  post 'evento/:id', to: 'eventos#delete_image', as: 'delete_image'
  get 'home/index'
  root to: 'home#index'
  get 'home/change_region'
  get 'home/politicas'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if params[:comuna].present? || params[:region].present?
      if params[:comuna].present?
        @comuna = Comuna.find(params[:comuna].to_i)
        @eventos = Evento.all.where(comuna_id: params[:comuna].to_i)
        params[:region] = @comuna.region.id
        @comunas = Region.find(params[:region].to_i).comunas
      else
        @region = Region.find(params[:region].to_i)
        @eventos = @region.eventos
      end
      @cantidad = @eventos.count
  	else
  		@eventos = Evento.all
  	end
    @regiones = Region.all
  end

  def change_region
  	@region = Region.find(params[:region_id])
  	@comunas = @region.comunas
  end

  def politicas
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/change_region.js.erb
$('#comuna').children().remove();


$('#comuna').append($('<option>',
    {
        value: "",
        disabled: "",
        selected: "",
        text : ""
    }));

<% @comunas.each do |c| %>
  $('#comuna').append($('<option>',
    {
        value: "<%= c.id %>",
        text : "<%= c.nombre %>",
    }));
<% end %>

$('#comuna').formSelect();

app/views/home/index.html.erb
 <div class="wavy">
 	<span style="--i:1;">O</span>
 	<span style="--i:2;">l</span>
 	<span style="--i:3;">l</span>
 	<span style="--i:4;">a</span>
 	<span style="--i:5;">&nbsp</span>
 	<span style="--i:6;">C</span>
 	<span style="--i:7;">o</span>
 	<span style="--i:8;">m</span>
 	<span style="--i:9;">ú</span>
 	<span style="--i:10;">n</span>
 </div>

<div class="container">
	<br>
	<section>
		<h5>Bienvenido:</h5>
		<p>
			En este sitio podrás buscar y publicar tu olla común, registrare e ingresa tu evento de ayuda.
		<p>
		</p>
			En estos tiempos difíciles lo importante es ayudarnos entre todos, por lo mismo, por favor, que tu información sea verdadera ya que la necesidad puede llegar a todos.
		</p>
	</section>

	<div class="input-field col s12">
		<select id="region" name="region" onchange="ShowSelectedRegion();">
		  <% if ! params[:region].present? %>
		  	<option value="" disabled selected></option>
		  <% end %>
		  <% @regiones.each do |r| %>
			    <option value="<%= r.id %>" <%= params[:region].to_i == r.id ? 'selected' : '' %>><%= r.nombre %></option>
		  <% end %>
		</select>
		<label>Seleccione Region</label>
	  </div>

	 <div class="input-field col s6">
	 	<% if @comunas.present? %>
	 		<select id="comuna" name="comuna" onchange="ShowSelectedComuna();">
        <% if ! params[:comuna].present? %>
			  	<option value="" disabled selected></option>
			  <% end %>
			  <% @comunas.each do |c| %>
			  	<option value="<%= c.id %>" <%= params[:comuna].to_i == c.id ? 'selected' : '' %>><%= c.nombre %></option>
			  <% end %>
			</select>
	 	<% else %>
			<select id="comuna" name="comuna" onchange="ShowSelectedComuna();">
			  <% if ! params[:comuna].present? %>
			  	<option value="" disabled selected></option>
			  <% end %>
			  <% @regiones.each do |r| %>
			  	<optgroup label="<%= r.nombre %>">
			  		<% r.comunas.each do |c| %>
				    	<option value="<%= c.id %>" <%= params[:comuna].to_i == c.id ? 'selected' : '' %>><%= c.nombre %></option>
				    <% end %>
			  	</optgroup>
			  <% end %>
			</select>
		<% end %>

		<label>Seleccione Comuna</label>

    <!--  action buttons -->
		  <div class="col s6 center-align">
          <% if params[:comuna].present? && params[:region].present? %>
            <a class="btn-floating btn-large green pulse"
            href='<%= params[:comuna].present? ?
            "#{home_index_path}#{"?comuna=#{params[:comuna].to_i}"}" : "" %>'
            id="search"><i class="material-icons">search</i></a>
          <%else%>
            <% if params[:comuna].present? %>
              <a class="btn-floating btn-large green pulse"
              href='<%= params[:comuna].present? ?
              "#{home_index_path}#{"?comuna=#{params[:comuna].to_i}"}" : "" %>'
              id="search"><i class="material-icons">search</i></a>
            <% else %>
          		<a class="btn-floating btn-large green pulse"
              href='<%= params[:region].present? ?
              "#{home_index_path}#{"?region=#{params[:region].to_i}"}" : "#{home_index_path}" %>'
              id="search"><i class="material-icons">search</i></a>
            <% end %>
          <% end %>

          <a class="btn-floating btn-large cyan pulse"
          href="<%= home_index_path %>"
          id="search"><i class="material-icons">refresh</i></a>

      	</div>
	 </div>
	</div>
</div>

<section>
	<% if @comuna.present? %>
		<div class="container">
       		<p><%= @cantidad %><%= @cantidad == 1 ? ' Registro encontrado' : ' Registros encontrados' %> en la comuna de : <%= @comuna.nombre.capitalize %> , Region : <%= @comuna.region.nombre.capitalize %> </p>
       	</div>
    <% end %>
    <% if @region.present? %>
    	<div class="container">
       		<p><%= @cantidad %><%= @cantidad == 1 ? ' Registro encontrado' : ' Registros encontrados' %><%= " en la Region #{ @region.nombre }" %> </p>
       	</div>
    <% end %>
	<%= render 'shared/eventos' , evento: nil %>
</section>

 <script>
 	$(document).ready(function(){
     $('select').formSelect();
  	});

 	function ShowSelectedRegion(){
		var region = parseInt(document.getElementById("region").value);
	 	$.ajax({
	      type: 'GET',
	      url: "<%= home_change_region_path %>",
	      dataType: "script",
	      data: {region_id: region}
	    });
	    $('#search').attr("href","<%= home_index_path + '?region='%>" + region);
 	}

 	function ShowSelectedComuna(){
 		var comuna = parseInt(document.getElementById("comuna").value);
 		$('#search').attr("href","<%= home_index_path + '?comuna='%>" + comuna);
 	}
 </script>