config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip =>  [:registrations], controllers:{
  	omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :eventos
  post 'evento/:id', to: 'eventos#delete_image', as: 'delete_image'
  get 'home/index'
  root to: 'home#index'
  get 'home/change_region'
  get 'home/politicas'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/evento.rb
class Evento < ApplicationRecord
  belongs_to :comuna
  belongs_to :user
  validates :descripcion, presence: true
  has_one_attached :image
  def pertenece_to_user(user)
  	if user.present? && self.user_id == user.id
  		true
  	else
  		false
  	end
  end

  def descripcion_short
    self.descripcion + (' ' * 50)
  end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_evento, only: [:show, :edit, :update, :destroy, :delete_image]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all.order(:comuna_id)
    authorize @eventos
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @eventos = Evento.where(id: params[:id])
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
    authorize @evento
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)
    @evento.user = current_user
    authorize @evento
    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    if @evento.image.attached?
      @evento.image.purge
    end
    @evento.destroy
    respond_to do |format|
      if current_user.admin?
        format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      else
        format.html { redirect_to new_evento_url, notice: 'Evento was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  def delete_image
    if @evento.image.attached?
      @evento.image.purge
    end
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
      authorize @evento
    end

    # Only allow a list of trusted parameters through.
    def evento_params
      params.require(:evento).permit(:comuna_id, :descripcion, :organizacion, :encargado, :direccion, :dias_horarios, :organizador, :image)
    end
end

app/helpers/eventos_helper.rb
module EventosHelper
	def with_evento?
   	 if current_user.evento.nil?
   	 	false
   	 else
   	 	if current_user.evento.persisted?
   	 		true
   	 	else
   	 		false
   	 	end
   	 end
   end
end

app/views/eventos/_form.html.erb
<div class="container">
  <%= form_with(model: evento, local: true) do |form| %>
    <% if evento.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

        <ul>
        <% evento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-field">    
      <i class="material-icons prefix">navigate_next</i>
      <select id="comuna" name="comuna">
      <% if evento.comuna_id.nil? %>
        <option value="" disabled selected></option>
      <% end %>
      <% Region.all.each do |r| %>
        <optgroup label="<%= r.nombre %>">
          <% r.comunas.each do |c| %>
            <% if evento.comuna_id.nil? %>
              <option value="<%= c.id %>"><%= c.nombre %></option>
            <% else %>
              <option value="<%= c.id %>" <%= evento.comuna_id == c.id ? 'selected' : '' %>><%= c.nombre %></option>
            <% end %>
          <% end %>
        </optgroup>
      <% end %>
      </select>

      <label>Seleccione Comuna</label>
      <%= form.hidden_field :comuna_id %>  
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :descripcion %>
      <%= form.text_area :descripcion %>
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :organizacion %>
      <%= form.text_field :organizacion %>  
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :encargado %>
      <%= form.text_field :encargado %>
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :direccion %>
      <%= form.text_field :direccion %>
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :dias_horarios %>
      <%= form.text_area :dias_horarios %>
    </div>

    <div class="input-field">
      <i class="material-icons prefix">navigate_next</i>
      <%= form.label :organizador %>
      <%= form.text_field :organizador %>
    </div>
    
      <div class="input-field">
        <div class="row">
          <div class="col s12">
            <div class="custom-file">
              <i class="material-icons prefix">navigate_next</i>
              <%= form.label :image %><br>
              <%= form.file_field :image %>
            </div>
          </div>
          <div class="col offset-s6 s3">
            <br>
            <% if evento.image.attached? %>
              <%= image_tag evento.image.variant(resize: "100x100").processed, id:"image_evento" %>
            <% end %>
          </div>
          <div class="col s3" id="image_evento_btns">
            <% if evento.image.attached? %>
              <%= link_to '<i class="material-icons">delete</i>'.html_safe, delete_image_path(evento, format: :js), class: 'btn-floating btn-large red pulse', method: :post, remote: true, data: { confirm: 'Are you sure?' } %>
              <label>Quitar Imagen</label>
            <% end %>
          </div>
        </div>
      </div>
    

    <div class="actions">
      <div class="row">
        <div class="col s12 center">
          <%= form.submit "Guardar" %>
        </div>
      </div>
    </div>

  <% end %>
</div>

<script>
  $(document).ready(function(){
     $('select').formSelect();
     M.updateTextFields();
     document.getElementById('comuna').addEventListener('change',ShowSelectedComuna,false);
     function ShowSelectedComuna(){
      var comuna = parseInt(document.getElementById("comuna").value);
      $('#evento_comuna_id').attr("value",comuna);
     }
    });
</script>

app/views/eventos/delete_image.js.erb
$("#image_evento").fadeOut(300);
$("#image_evento_btns").fadeOut(300);

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>


<div class="row">
    <div class="col s12 center">
		<%= link_to '<i class="material-icons">keyboard_backspace</i>'.html_safe, :back, class: 'btn-floating btn-large cyan pulse' %>
	</div>
</div>

app/views/eventos/index.html.erb
<h1>Eventos</h1>

<table class="responsive-table centered striped">
  <thead>
    <tr>
      <th>Creada por</th>
      <th>Comuna</th>
      <th>Descripcion</th>
      <th>Organizacion</th>
      <th>Dias horarios</th>
      <th>Organizador</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.user.email %></td>
        <td><%= evento.comuna.nombre.capitalize %></td>
        <td><%= evento.descripcion %></td>
        <td><%= evento.organizacion %></td>
        <td><%= evento.dias_horarios %></td>
        <td><%= evento.organizador %></td>
      
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<% if ! with_evento? %>
	<%= render 'form', evento: @evento %>
<% end %>

<%= link_to '<i class="material-icons">keyboard_backspace</i>'.html_safe, :back ,class: 'btn-floating btn-large cyan pulse'%>

app/views/eventos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col offset-s1 s10">
      <%= render 'shared/evento' , evento: @eventos%>
    </div>
    <div class="col s12">
      <h5>Datos: </h5>
      <ul class="collection">
        <li class="collection-item"><label>Email:</label> <%= @evento.user.email %></li>
        <li class="collection-item"><label>Comuna:</label> <%= @evento.comuna.nombre.capitalize %></li>
        <li class="collection-item"><label>Organización:</label> <%= @evento.organizacion %></li>
        <li class="collection-item"><label>Encargado:</label> <%= @evento.encargado %></li>
        <li class="collection-item"><label>Direccion:</label> <%= @evento.direccion %></li>
        <li class="collection-item"><label>Horario:</label> <%= @evento.dias_horarios %></li>
        <li class="collection-item"><label>Oganizador:</label> <%= @evento.organizador %></li>
      </ul>
    </div> 
  </div>
  <div class="row">
    <div class="col s12 center">
      <%= link_to '<i class="material-icons">keyboard_backspace</i>'.html_safe, root_path, class: 'btn-floating btn-large cyan pulse' %>
    

      <% if user_signed_in? && (@evento.user_id == current_user.id || current_user.admin?) %>
       |
        <%= link_to '<i class="material-icons">edit</i>'.html_safe , edit_evento_path(@evento), class: 'btn-floating btn-large gren pulse' %>
        |
        <%= link_to '<i class="material-icons">delete
      </i>'.html_safe, evento_path(@evento), class: 'btn-floating btn-large red pulse',method: :delete, data: { confirm: 'Are you sure?' } %> 
        
      <% end %>
    </div>
  </div>  
</div>